title: 兵疯王座
subtitle: 贱圣的地盘
link: http://albert-feng.github.io/
meta:
  description: 页面meta中的description
  keywords: !!seq
    - 关键词1
    - 关键词2
    - 关键词3
  author: 页面meta中的author
master:
  name: 贱圣
  about: Python码农@帝都
  email: fwg1989@gmail.com
rss:
  title: RSS源标题
  desc: RSS源描述
  lang: zh-cn
  max: 10
copyright:
  owner: 版权所有方
  beginYear: 2011
  endYear: 2013
  ICP: 备案号
theme: default
codetheme: light
