title: 兵疯王座
subtitle: 记录程序员路上的点滴
link: http://albert-feng.github.io/
meta:
  description: Life is short, I use Python
  keywords: !!seq
    - python
    - linux
    - network
    - cloud computing
    - sdn
  author: 贱圣
master:
  name: 贱圣
  about: 一只爱Dota,爱踢球的码农
  email: fwg1989@gmail.com
rss:
  title: 兵疯王座
  desc: 记录程序员路上的点滴
  lang: zh-cn
  max: 10
copyright:
  owner: 版权所有方
  beginYear: 2013
  endYear: 2014
  ICP: 备案号：啥也没有
theme: default
codetheme: light
